[build-system]
requires=["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "hand-rl"
version = "0.1.0"
description = "Rice Robotics Hand Command"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "numpy",
  "torch",
  "torchvision",
  "pyyaml",
  "tensorboard>=2.20.0",
  "jsonschema",
  "jsonschema-gentypes",
  "tensordict",
  "pygame",
  "genesis-world @ git+https://github.com/Genesis-Embodied-AI/Genesis.git",
  "rsl-rl-lib==5.*",
  "cowsay>=6.1",
  "lolcat>=1.4",
  "pretty_midi>=0.2.11,<0.3",
  "jaxtyping>=0.3.11",
  "beartype>=0.22.9",
  "pydantic>=2.13.5",
]

[project.scripts]
ruka = "scripts.ruka:main"
generate_schema = "scripts.generate_schema:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["scripts*", "src*"]

[tool.setuptools.package-data]
config = ["*.yaml", "schemas/*.json"]

[project.optional-dependencies]
sheet = [
  "music21>=9.1,<10",
]

[dependency-groups]
dev = [
  "basedpyright>=1.40.1",
  "docformatter>=1.7.8",
  "ruff>=0.16.8",
]
