# yaml-language-server: $schema=https://github.com/rice-robotics-club/hand-rl/schema.json
runner:
  class_name: OnPolicyRunner
  save_interval: 100
  obs_groups:
    actor:
      - position
      - velocity
      - orientation
    critic:
      - position
      - velocity
      - orientation
  num_steps_per_env: 24
  algorithm:
    class_name: PPO
  actor:
    class_name: MLPModel
    distribution_cfg:
      class_name: GaussianDistribution
  critic:
    class_name: MLPModel
    distribution_cfg:
      class_name: GaussianDistribution
env:
  class_name: RukaEnv
  fingers: 100
system:
  class_name: RukaSim
  num_envs: 100
