# yaml-language-server: $schema=schemas/schema.json
runner:
  class_name: OnPolicyRunner
  save_interval: 100
  obs_groups:
    actor:
      - position
      - velocity
      - orientation
    critic:
      - position
      - velocity
      - orientation
  num_steps_per_env: 24
  algorithm:
    class_name: PPO
  actor:
    class_name: MLPModel
    distribution_cfg:
      class_name: GaussianDistribution
  critic:
    class_name: MLPModel
    distribution_cfg:
      class_name: GaussianDistribution
env:
  class_name: src.env.ruka_env:RukaEnv
  fingers: 100
system:
  class_name: src.sim.ruka_sim:RukaSim
  num_envs: 100
